---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chuthe-api
  name: chuthe-api-svc
spec:
  type: ClusterIP
  # type: ExternalName
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: chuthe-api
