apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-secret
data:
  DEBUG: "VHJ1ZQ=="
  SECRET_KEY: "I2hic3NyJl9jMjBlMD0yaDJyd2I2cjZpZWYzQF5qJj1eOSgzJnY0aUBqaHNpPV4pJWoK"
  DATABASE_NAME: "ZGphbmdvX3Rlc3Q="
  DATABASE_URL: "cG9zdGdyZXNxbC1wb3N0Z3Jlc3FsLWhhLXBncG9vbA=="
  DATABASE_PORT: "NTQzMg=="
  DATABASE_USER: "cG9zdGdyZXM="
  DATABASE_PASSWORD: "YWRtaW4xMjM="
  BROKER_USER: "dXNlcg=="
  BROKER_PASSWORD: "M3A1NEQ1WnRhQw=="

---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIk1IZzNZenBoYm1oaGJtY3hNak09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: dockercred
  namespace: default
type: kubernetes.io/dockerconfigjson
