apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuthe-api
  labels:
    app: chuthe-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chuthe-api
  template:
    metadata:
      labels:
        app: chuthe-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1.example.com
                - worker2.example.com
                - worker3.example.com
                - worker4.example.com
      containers:
      - name: chuthe
        image: docker.io/0x7c/chuthe:latest
        command: ["/bin/sh"]
        args: ["-c", "daphne chuthe.asgi:application -b 0.0.0.0"]
        imagePullPolicy: Always
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_PORT
        envFrom:
          - secretRef:
              name: app-secret
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 8000
        # command: ["pwd"]

