# -*- mode: ruby -*-
# vi: set ft=ruby :

# ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "k8s_common.sh"
  # config.vm.provision :reload
  WorkerNodes = 2
  DatabaseNodes = 2
  Ingress = 2
  LB = 1
  MQ = 1
  # Kubernetes Master Server
  config.vm.define "master" do |node|
    node.vm.box               = "centos/8"
    node.vm.box_check_update  = false
    node.vm.hostname          = "master.example.com"
    node.vm.network "public_network", ip: "192.168.1.100",  bridge: "enp6s0"
    node.vm.provider :virtualbox do |v|
      v.name    = "master"
      v.memory  = 4096
      v.cpus    = 4
    end
    node.vm.provision "shell", path: "k8s_master.sh"
  end

# Kubernetes Worker Nodes
  (1..WorkerNodes).each do |i|
    config.vm.define "worker#{i}" do |node|
      node.vm.box               = "centos/8"
      node.vm.box_check_update  = false
      node.vm.hostname          = "worker#{i}.example.com"
      node.vm.network "public_network", ip: "192.168.1.20#{i}", bridge: "enp6s0"
      node.vm.provider :virtualbox do |v|
        v.name    = "worker#{i}"
        v.memory  = 3072
        v.cpus    = 4
      end
      node.vm.provision "shell", path: "k8s_worker.sh"
    end
  end

  (1..DatabaseNodes).each do |i|
    config.vm.define "database#{i}" do |node|
      node.vm.box               = "centos/8"
      node.vm.box_check_update  = false
      node.vm.hostname          = "database#{i}.example.com"
      node.vm.network "public_network", ip: "192.168.1.2#{i}", bridge: "enp6s0"
      node.vm.provider :virtualbox do |v|
        v.name    = " database#{i}"
        v.memory  = 2048
        v.cpus    = 2
      end
      node.vm.provision "shell", path: "k8s_worker.sh"
    end
  end

  (1..Ingress).each do |i|
    config.vm.define "ingress#{i}" do |node|
      node.vm.box               = "centos/8"
      node.vm.box_check_update  = false
      node.vm.hostname          = "ingress#{i}.example.com"
      node.vm.network "public_network", ip: "192.168.1.4#{i}", bridge: "enp6s0"
      node.vm.provider :virtualbox do |v|
        v.name    = " ingress#{i}"
        v.memory  = 1024
        v.cpus    = 2
      end
      node.vm.provision "shell", path: "k8s_worker.sh"
    end
  end

  (1..LB).each do |i|
    config.vm.define "lb#{i}" do |node|
      node.vm.box               = "centos/8"
      node.vm.box_check_update  = false
      node.vm.hostname          = "lb#{i}.example.com"
      node.vm.network "public_network", ip: "192.168.1.5#{i}", bridge: "enp6s0"
      node.vm.provider :virtualbox do |v|
        v.name    = "lb#{i}"
        v.memory  = 1024
        v.cpus    = 2
      end
      node.vm.provision "shell", path: "k8s_worker.sh"
    end
  end

  (1..MQ).each do |i|
    config.vm.define "mq#{i}" do |node|
      node.vm.box               = "centos/8"
      node.vm.box_check_update  = false
      node.vm.hostname          = "mq#{i}.example.com"
      node.vm.network "public_network", ip: "192.168.1.9#{i}", bridge: "enp6s0"
      node.vm.provider :virtualbox do |v|
        v.name    = "mq#{i}"
        v.memory  = 2048
        v.cpus    = 4
      end
      node.vm.provision "shell", path: "k8s_worker.sh"
    end
  end
end
