apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuthe-api
  labels:
    app: chuthe-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: chuthe-api
  template:
    metadata:
      labels:
        app: chuthe-api
    spec:
      containers:
      - name: chuthe
        image: docker.io/0x7c/chuthe:latest
        imagePullPolicy: Always
        # envFrom:
        #   - secretRef:
        #       name: django-k8s-web-prod-env
        # env:
        #   - name: PORT
        #     value: "8002"
        ports:
        - containerPort: 80
      # imagePullSecrets:
      #   - name: 
