apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
data:
  {{- range $key, $val := .Values.secrets.app }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-crcred
data:
  {{- range $key, $val := .Values.secrets.cr }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}

type: kubernetes.io/dockerconfigjson
