apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq
  labels:
    type: local
spec:
  storageClassName: rabbitmq
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/rabbitmq"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres0
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/pv0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres1
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres2
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/pv2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres3
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/pv3"
---




apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data0
  labels:
    type: local
spec:
  storageClassName: elasticsearch-data
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/elasticsearch"
  mountOptions:
    - hard
    - nfsvers=4.1
  -
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data1
  labels:
    type: local
spec:
  storageClassName: elasticsearch-data
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/elasticsearch"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-admin0
  labels:
    type: local
spec:
  storageClassName: elasticsearch-admin
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/elasticsearch"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-admin1
  labels:
    type: local
spec:
  storageClassName: elasticsearch-admin
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/elasticsearch"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-admin2
  labels:
    type: local
spec:
  storageClassName: elasticsearch-admin
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/elasticsearch"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-kibana
  labels:
    type: local
spec:
  storageClassName: elasticsearch-kibana
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/elasticsearch"
---
