apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv0
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 15Gi
    # storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/pv0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 15Gi
    # storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv2
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 15Gi
    # storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/pv2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv3
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 15Gi
    # storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/pv3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-files
  labels:
    type: local
spec:
  storageClassName: django-app
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.5
    path: "/srv/nfs/django-static"
---


