apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: rabbitmq

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: rabbitmq
  storageClassName: rabbitmq
  volumeMode: Filesystem

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-nfs-pv2
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-nfs-pv3
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
