apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: example.com/external-nfs
parameters:
  archiveOnDelete: "false"
  server: 192.168.1.5
  path: /srv/nfs/k8s_play
  readOnly: "false"
allowVolumeExpansion: true
reclaimPolicy: Delete
