apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: api
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-04-10T15:29:40Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: api-0.1.0
  name: api
  namespace: default
  resourceVersion: "188279"
  uid: a5d6e98c-7ac4-4442-8d41-17b1fcbdec31
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: api
      app.kubernetes.io/name: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: api
        app.kubernetes.io/name: api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1.example.com
                - worker2.example.com
                - worker3.example.com
                - worker4.example.com
      containers:
      - envFrom:
        - configMapRef:
            name: api
        - secretRef:
            name: api
        image: docker.io/0x7c/chuthe:latest
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: api-crcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: api
      serviceAccountName: api
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-04-10T15:29:43Z"
    lastUpdateTime: "2022-04-10T15:29:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-04-10T15:29:40Z"
    lastUpdateTime: "2022-04-10T15:29:43Z"
    message: ReplicaSet "api-75fb887746" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
